# Copyright 2026 Phillip Cloud
# Licensed under the Apache License, Version 2.0

version: "2"

linters:
  enable:
    # Type safety
    - forcetypeassert
    - unconvert
    - asasalint

    # Error handling
    - errorlint
    - errchkjson

    # Bug prevention
    - gocritic
    - gosec
    - durationcheck
    - exhaustive
    - fatcontext
    - copyloopvar

    # Resource & network safety
    - sqlclosecheck
    - bodyclose
    - nilerr

    # Code quality
    - goconst
    - dupword
    - asciicheck

  settings:
    exhaustive:
      default-signifies-exhaustive: true

    goconst:
      min-occurrences: 5
      ignore-tests: true

    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - ifElseChain

  exclusions:
    rules:
      # staticcheck nil-after-Fatal false positives in tests
      - linters: [staticcheck]
        path: _test\.go
        text: "SA5011"
